image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository

deploy:jdk8:
  stage: deploy
  script:
    - mvn clean package -Dmaven.test.skip=true
    - find / -name spring-boot-starter-parent-2.6.3.pom
  only:
    - master
