stages:
  - deploy

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository

deploy:jdk8:
  stage: deploy
  script:
    - mvn clean package -Dmaven.test.skip=true
    - find / -name spring-boot-starter-parent-2.6.3.pom
  artifacts:
    paths:
      - target/hello-dockerfile-*-SNAPSHOT.jar
  only:
    - master
